DjangoBlog/urls.py
from django.contrib import admin
from django.urls import path,include

from article import views
from django.conf import settings#settingsten media importu
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index,name="index"),#oluşturulan template ın urlsi buraya tanıtılır fonksiyon eklenir
                              # fonksiyonu ise article->views.py altına yazılır
    path('about/',views.about,name="about"),
    path('articles/',include("article.urls")),#articles ile ilgili url gelince include içerisinden 
    # ilgili yere gidip orada arayacak 
    
    path('user/',include("user.urls")),#ilgili url leri user url ye yönlendirir
    
  
    
]

handler404 = 'core.views.error_404_view'
handler500 = 'core.views.error_500_view'
handler403 = 'core.views.error_403_view'
handler405 = 'core.views.error_405_view'
handler429 = 'core.views.error_429_view'

urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

article/urls.py
from django.contrib import admin
from django.urls import path
from . import views# fonksiyonların bulunduğu yeri import etme


app_name="article"

urlpatterns = [
    path('dashboard/',views.dashboard,name="dashboard"),
    path('addarticle/',views.addarticle,name="addarticle"),
    path('article/<int:id>/',views.detail,name="detail"),
    path('update/<int:id>',views.updateArticle,name="update"),
    path('delete/<int:id>',views.deleteArticle,name="delete"),
    path('',views.articles,name="articles"),
    path('comment/<int:id>',views.addComment,name="comment"),
    path('like/<int:article_id>/',views.toggle_article_like, name="toggle_article_like"),
    path('comment-like/<int:comment_id>/',views.toggle_comment_like,name="toggle_comment_like"),
]

user/urls.py
from django.contrib import admin
from django.urls import path
from . import views# fonksiyonların bulunduğu yeri import etme

app_name="user"

urlpatterns=[
    path('register/',views.register,name="register"),
    path('login/',views.loginUser,name="login"),
    path('logout/',views.logoutUser,name="logout"),
    path("update-profile/", views.update_profile, name="update_profile"),
    path("contact/",views.contact,name="contact"),
]

templates/includes/footer.html
  <footer id="footer" class="footer position-relative light-background">

    <div class="container">
      <div class="row gy-5">

        <div class="col-lg-4">
          <div class="footer-brand">
            <a href="index.html" class="logo d-flex align-items-center mb-3">
              <span class="sitename">Dajngo Blog</span>
            </a>
            <p class="tagline">Django altyapısıyla geliştirilmiş bu platform, dinamik içerik yönetimi, kullanıcı etkileşimi ve modern arayüz tasarımı örneklerini bir arada sunar.</p>

            <div class="social-links mt-4">
              <a href="https://www.linkedin.com/in/mustafaesen" aria-label="Facebook" target="_blank" rel="noopener noreferrer"><i class="bi bi-facebook"></i></a>
              <a href="https://github.com/mustafaaesen" aria-label="Instagram" target="_blank" rel="noopener noreferrer"><i class="bi bi-instagram"></i></a>
              <a href="https://www.linkedin.com/in/mustafaesen" target="_blank" rel="noopener noreferrer" aria-label="LinkedIn" ><i class="bi bi-linkedin"></i></a>
              <a href="https://github.com/mustafaaesen" aria-label="Github" target="_blank" rel="noopener noreferrer"><i class="bi bi-github"></i></a>
               <a href="https://www.linkedin.com/in/mustafaesen" aria-label="Twitter" target="_blank" rel="noopener noreferrer"><i class="bi bi-twitter-x"></i></a>
              <a href="https://mustafaesen.com.tr/" aria-label="Dribbble" target="_blank" rel="noopener noreferrer"><i class="bi bi-dribbble"></i></a>
            </div>
          </div>
        </div>

        <div class="col-lg-6">
          <div class="footer-links-grid">
            <div class="row">
              <div class="col-6 col-md-4">
                <h5>Site İçi</h5>
                <ul class="list-unstyled">
                  <li><a href="{% url 'about' %}">Hakkında</a></li>
                  <li><a href="{% url 'about' %}#team">Popüler Yazarlar</a></li>
                  <li><a href="{% url 'article:articles' %}">Makaleler</a></li>
                  <li><a href="{% url 'article:dashboard' %}">Kontrol Paneli</a></li>
                </ul>
              </div>
              
              <div class="col-6 col-md-4">
                <h5>Site İçi</h5>
                <ul class="list-unstyled">
                  <li><a href="{% url 'user:register' %}">Kayıt Ol</a></li>
                  <li><a href="{% url 'index' %}">Anasayfa</a></li>
                  <li><a href="{% url 'user:contact' %}">İletişim</a></li>
                  
                </ul>
              </div>
            </div>
          </div>
        </div>

        <div class="col-lg-2">
          <div class="footer-cta">
            <h5>Bağlan</h5>
            <a href="{% url 'user:contact' %}" class="btn btn-outline">İLETİŞİME GEÇ</a>
          </div>
        </div>

      </div>
    </div>

    <div class="footer-bottom">
      <div class="container">
        <div class="row">
          <div class="col-12">
            <div class="footer-bottom-content">
              <p class="mb-0">© <strong>Dajngo Blog</strong>. All rights reserved.</p>
              <div class="credits">
                <!-- All the links in the footer should remain intact. -->
                <!-- You can delete the links only if you've purchased the pro version. -->
                <!-- Licensing information: https://bootstrapmade.com/license/ -->
                <!-- Purchase the pro version with working PHP/AJAX contact form: [buy-url] -->
                Made by <a href="https://mustafaesen.com.tr/" target="_blank" rel="noopener noreferrer">mustafaesen</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

  </footer>

templates/includes/navbar.html
<header id="header" class="header d-flex align-items-center position-relative">
  <div class="container position-relative d-flex align-items-center justify-content-between">

    <a href="{% url 'index' %}" class="logo d-flex align-items-center me-auto me-xl-0">
      <h1 class="sitename">Dajngo Blog</h1>
    </a>

    <nav id="navmenu" class="navmenu">
      <ul>
        <li>
          <a href="{% url 'index' %}"
             class="{% if request.resolver_match.url_name == 'index' %}active{% endif %}">
             Anasayfa
          </a>
        </li>

        <li>
          <a href="{% url 'about' %}"
             class="{% if request.resolver_match.url_name == 'about' %}active{% endif %}">
             Hakkında
          </a>
        </li>

        <li>
          <a href="{% url 'article:articles' %}"
             class="{% if request.resolver_match.url_name == 'articles' %}active{% endif %}">
             Makaleler
          </a>
        </li>

        {% if request.user.is_authenticated %}
          <li>
            <a href="{% url 'article:dashboard' %}"
               class="{% if request.resolver_match.url_name == 'dashboard' %}active{% endif %}">
               Kontrol Paneli
            </a>
          </li>
          <li>
            <a href="{% url 'user:logout' %}"
               class="{% if request.resolver_match.url_name == 'logout' %}active{% endif %}">
               Çıkış Yap
            </a>
          </li>
        {% else %}
          <li>
            <a href="{% url 'user:login' %}"
               class="{% if request.resolver_match.url_name == 'login' %}active{% endif %}">
               Giriş Yap
            </a>
          </li>
        {% endif %}

        <li>
          <a href="{% url 'user:register' %}"
             class="{% if request.resolver_match.url_name == 'register' %}active{% endif %}">
             Kayıt Ol
          </a>
        </li>

        <li>
          <a href="{% url 'user:contact' %}"
             class="{% if request.resolver_match.url_name == 'contact' %}active{% endif %}">
             İletişim
          </a>
        </li>
      </ul>
      <i class="mobile-nav-toggle d-xl-none bi bi-list"></i>
    </nav>

    <div class="header-social-links">
      <a href="https://github.com/mustafaaesen" target="_blank" rel="noopener noreferrer"><i class="bi bi-twitter-x"></i></a>
      <a href="https://www.linkedin.com/in/mustafaesen" target="_blank" rel="noopener noreferrer"><i class="bi bi-facebook"></i></a>
      <a href="https://github.com/mustafaaesen" target="_blank" rel="noopener noreferrer"><i class="bi bi-instagram"></i></a>
      <a href="https://www.linkedin.com/in/mustafaesen" target="_blank" rel="noopener noreferrer"><i class="bi bi-linkedin"></i></a>
      <a href="https://github.com/mustafaaesen" target="_blank" rel="noopener noreferrer"><i class="bi bi-github"></i></a>
      <a href="https://www.mustafaesen.com.tr" target="_blank" rel="noopener noreferrer"><i class="bi bi-globe2"></i></a>
    </div>

  </div>
</header>